### ISSUE TITLE
Feel free to grab any code you want from aioruckus

### ISSUE THREAD

**Issue by ms264556** [lanrat/ruckus-clients#1]
I also hit the AJAX endpoints, and I have plenty of code to handle weird bugs and corner cases in the login process.

My code is no-attribution licensed, so you're welcome to grab anything you find useful.

https://github.com/ms264556/aioruckus

```python
from aioruckus import AjaxSession
import asyncio

async def users_test():
    async with AjaxSession.async_create("<ruckus ip>", "<ruckus user>", "<ruckus password>") as session:
        ruckus = session.api
        active_clients = await ruckus.get_active_clients()

asyncio.run(users_test())
```

**Comment by ms264556** [comment]
Actually, I'm not sure why you don't just use aioruckus directly, if this is for Home Assistant.

I structured aioruckus specifically the way Home Assistant documentation recommended.

**Comment by lanrat** [comment]
aioruckus looks great!

I wrote the code in this repository years ago for another project and put it here as a potential solution to the current issue with Home Assistant. Your library looks better and we should use that.

Thanks for making it!
